[package]
name = "wengine"
version = "0.1.0"
authors = ["Ken Reed <kenakioreed@gmail.com>"]
edition = "2021"

[workspace]
members = [ "demo"]

[dependencies]
wasm-bindgen = "0.2.43"
js-sys = "0.3.20"
wasm-bindgen-futures="*"
ws_stream_wasm = "*"
futures = "*"

[dependencies.web-sys]
version = "0.3.20"
features = [
  'DomRect',
  'CanvasRenderingContext2d',
  'MouseEvent',
  'ErrorEvent',
  'MessageEvent',
  'WebSocket',
  'Performance',
  'AudioContext',
  'AudioBuffer',
  'AudioNode',
  'AudioBufferSourceNode',
  'AudioDestinationNode',
  'Document',
  'Element',
  'HtmlCanvasElement',
  'KeyboardEvent',
  'Node',
  'WebGlBuffer',
  'WebGlRenderingContext',
  'WebGlProgram',
  'WebGlShader',
  'WebGlUniformLocation',
  'WebGlTexture',
  'Window',
]

[profile.release]
opt-level = 'z'
lto = true
panic = 'abort'
