[package]
name = "wengine"
version = "0.1.0"
authors = ["Ken Reed <kenakioreed@gmail.com>"]
edition = "2021"

[workspace]
members = [ "demo"]

[dependencies]
wasm-bindgen = "0.2.43"
js-sys = "0.3.20"
wasm-bindgen-futures="*"
ws_stream_wasm = "*"
futures = "*"

[dependencies.web-sys]
version = "0.3.20"
features = [
  'DomRect',
  'CanvasRenderingContext2d',
  'MouseEvent',
  'ErrorEvent',
  'Performance',
  'Document',
  'Element',
  'HtmlCanvasElement',
  'KeyboardEvent',
  'Window',
]
